apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  namespace: hardening-demo
spec:
  volumes:
    - name: sec-ctx-vol
      hostPath:
        path: /etc
  containers:
    - name: sec-ctx-pod
      image: IMAGE_PLACEHOLDER
      command: ["sh", "-c", "sleep 999"]
      volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data
      securityContext:
        privileged: true
