apiVersion: v1
kind: Namespace
metadata:
  name: threatapps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-to-runtime-demo
  namespace: threatapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-to-runtime-demo
  template:
    metadata:
      labels:
        app: code-to-runtime-demo
    spec:
      containers:
        - name: code-to-runtime-demo
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: code-to-runtime-demo
  namespace: threatapps
spec:
  selector:
    app: code-to-runtime-demo
  ports:
    - port: 8080
      targetPort: 8080
