apiVersion: v1
kind: Pod
metadata:
  name: nginx-cap-sys-admin
  namespace: threatapps
spec:
  containers:
  - name: nginx-cap-sys-admin
    image: nginx
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  namespace: threatapps
spec:
  volumes:
  - name: sec-ctx-vol
    hostPath:
      path: /etc
  containers:
  - name: sec-ctx-pod
    image: nginx
    command: [ "sh", "-c", "sleep 999" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-as-root
  namespace: threatapps
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: nginx-as-root
    image: nginx
